// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  healthCheckHealthCheckGet,
  readApplicationsApiV1ApplicationsGet,
  createApplicationApiV1ApplicationsPost,
  deleteApplicationApiV1ApplicationsApplicationIdDelete,
  readApplicationApiV1ApplicationsApplicationIdGet,
  updateApplicationApiV1ApplicationsApplicationIdPatch,
  readContactsApiV1ContactsGet,
  createContactApiV1ContactsPost,
  deleteContactApiV1ContactsContactIdDelete,
  readContactApiV1ContactsContactIdGet,
  updateContactApiV1ContactsContactIdPatch,
  listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGet,
  createInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPost,
  listInterviewsApiV1InterviewsGet,
  createInterviewFlatApiV1InterviewsPost,
  deleteInterviewApiV1InterviewsInterviewIdDelete,
  readInterviewApiV1InterviewsInterviewIdGet,
  updateInterviewApiV1InterviewsInterviewIdPatch,
  listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGet,
  createPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPost,
  readPipelineHistoriesApiV1PipelineHistoryGet,
  createPipelineHistoryApiV1PipelineHistoryPost,
  deletePipelineHistoryApiV1PipelineHistoryHistoryIdDelete,
  readPipelineHistoryApiV1PipelineHistoryHistoryIdGet,
  updatePipelineHistoryApiV1PipelineHistoryHistoryIdPatch,
} from "../sdk.gen";
import {
  queryOptions,
  infiniteQueryOptions,
  type InfiniteData,
  type UseMutationOptions,
} from "@tanstack/react-query";
import type {
  HealthCheckHealthCheckGetData,
  ReadApplicationsApiV1ApplicationsGetData,
  ReadApplicationsApiV1ApplicationsGetError,
  CreateApplicationApiV1ApplicationsPostData,
  CreateApplicationApiV1ApplicationsPostError,
  CreateApplicationApiV1ApplicationsPostResponse,
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteData,
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteError,
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponse,
  ReadApplicationApiV1ApplicationsApplicationIdGetData,
  UpdateApplicationApiV1ApplicationsApplicationIdPatchData,
  UpdateApplicationApiV1ApplicationsApplicationIdPatchError,
  UpdateApplicationApiV1ApplicationsApplicationIdPatchResponse,
  ReadContactsApiV1ContactsGetData,
  ReadContactsApiV1ContactsGetError,
  ReadContactsApiV1ContactsGetResponse,
  CreateContactApiV1ContactsPostData,
  CreateContactApiV1ContactsPostError,
  CreateContactApiV1ContactsPostResponse,
  DeleteContactApiV1ContactsContactIdDeleteData,
  DeleteContactApiV1ContactsContactIdDeleteError,
  DeleteContactApiV1ContactsContactIdDeleteResponse,
  ReadContactApiV1ContactsContactIdGetData,
  UpdateContactApiV1ContactsContactIdPatchData,
  UpdateContactApiV1ContactsContactIdPatchError,
  UpdateContactApiV1ContactsContactIdPatchResponse,
  ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData,
  ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetError,
  ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponse,
  CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostData,
  CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostError,
  CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponse,
  ListInterviewsApiV1InterviewsGetData,
  ListInterviewsApiV1InterviewsGetError,
  ListInterviewsApiV1InterviewsGetResponse,
  CreateInterviewFlatApiV1InterviewsPostData,
  CreateInterviewFlatApiV1InterviewsPostError,
  CreateInterviewFlatApiV1InterviewsPostResponse,
  DeleteInterviewApiV1InterviewsInterviewIdDeleteData,
  DeleteInterviewApiV1InterviewsInterviewIdDeleteError,
  DeleteInterviewApiV1InterviewsInterviewIdDeleteResponse,
  ReadInterviewApiV1InterviewsInterviewIdGetData,
  UpdateInterviewApiV1InterviewsInterviewIdPatchData,
  UpdateInterviewApiV1InterviewsInterviewIdPatchError,
  UpdateInterviewApiV1InterviewsInterviewIdPatchResponse,
  ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData,
  ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetError,
  ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponse,
  CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostData,
  CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostError,
  CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponse,
  ReadPipelineHistoriesApiV1PipelineHistoryGetData,
  ReadPipelineHistoriesApiV1PipelineHistoryGetError,
  ReadPipelineHistoriesApiV1PipelineHistoryGetResponse,
  CreatePipelineHistoryApiV1PipelineHistoryPostData,
  CreatePipelineHistoryApiV1PipelineHistoryPostError,
  CreatePipelineHistoryApiV1PipelineHistoryPostResponse,
  DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteData,
  DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteError,
  DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponse,
  ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetData,
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchData,
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchError,
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponse,
} from "../types.gen";
import { client as _heyApiClient } from "../client.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl ||
      (options?.client ?? _heyApiClient).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthCheckHealthCheckGetQueryKey = (
  options?: Options<HealthCheckHealthCheckGetData>,
) => createQueryKey("healthCheckHealthCheckGet", options);

/**
 * Health Check
 * Stubbed health check for testing.
 */
export const healthCheckHealthCheckGetOptions = (
  options?: Options<HealthCheckHealthCheckGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCheckHealthCheckGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthCheckHealthCheckGetQueryKey(options),
  });
};

export const readApplicationsApiV1ApplicationsGetQueryKey = (
  options?: Options<ReadApplicationsApiV1ApplicationsGetData>,
) => createQueryKey("readApplicationsApiV1ApplicationsGet", options);

/**
 * List applications
 * Returns applications with interviews, contacts, and pipeline history preloaded.
 */
export const readApplicationsApiV1ApplicationsGetOptions = (
  options?: Options<ReadApplicationsApiV1ApplicationsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readApplicationsApiV1ApplicationsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readApplicationsApiV1ApplicationsGetQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const readApplicationsApiV1ApplicationsGetInfiniteQueryKey = (
  options?: Options<ReadApplicationsApiV1ApplicationsGetData>,
): QueryKey<Options<ReadApplicationsApiV1ApplicationsGetData>> =>
  createQueryKey("readApplicationsApiV1ApplicationsGet", options, true);

/**
 * List applications
 * Returns applications with interviews, contacts, and pipeline history preloaded.
 */
export const readApplicationsApiV1ApplicationsGetInfiniteOptions = (
  options?: Options<ReadApplicationsApiV1ApplicationsGetData>,
) => {
  return infiniteQueryOptions<
    unknown,
    ReadApplicationsApiV1ApplicationsGetError,
    InfiniteData<unknown>,
    QueryKey<Options<ReadApplicationsApiV1ApplicationsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ReadApplicationsApiV1ApplicationsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ReadApplicationsApiV1ApplicationsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readApplicationsApiV1ApplicationsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: readApplicationsApiV1ApplicationsGetInfiniteQueryKey(options),
    },
  );
};

/**
 * Create an application
 * Creates a new application and automatically logs an initial pipeline history entry (`None → pipeline_status`).
 */
export const createApplicationApiV1ApplicationsPostMutation = (
  options?: Partial<Options<CreateApplicationApiV1ApplicationsPostData>>,
): UseMutationOptions<
  CreateApplicationApiV1ApplicationsPostResponse,
  CreateApplicationApiV1ApplicationsPostError,
  Options<CreateApplicationApiV1ApplicationsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateApplicationApiV1ApplicationsPostResponse,
    CreateApplicationApiV1ApplicationsPostError,
    Options<CreateApplicationApiV1ApplicationsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createApplicationApiV1ApplicationsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an application
 * Deletes the application; associated PipelineHistory, Interviews, and links are removed via cascade.
 */
export const deleteApplicationApiV1ApplicationsApplicationIdDeleteMutation = (
  options?: Partial<
    Options<DeleteApplicationApiV1ApplicationsApplicationIdDeleteData>
  >,
): UseMutationOptions<
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponse,
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteError,
  Options<DeleteApplicationApiV1ApplicationsApplicationIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponse,
    DeleteApplicationApiV1ApplicationsApplicationIdDeleteError,
    Options<DeleteApplicationApiV1ApplicationsApplicationIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteApplicationApiV1ApplicationsApplicationIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

export const readApplicationApiV1ApplicationsApplicationIdGetQueryKey = (
  options: Options<ReadApplicationApiV1ApplicationsApplicationIdGetData>,
) =>
  createQueryKey("readApplicationApiV1ApplicationsApplicationIdGet", options);

/**
 * Get an application by id
 * Returns one application with interviews, contacts, and pipeline history.
 */
export const readApplicationApiV1ApplicationsApplicationIdGetOptions = (
  options: Options<ReadApplicationApiV1ApplicationsApplicationIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readApplicationApiV1ApplicationsApplicationIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readApplicationApiV1ApplicationsApplicationIdGetQueryKey(options),
  });
};

/**
 * Update an application
 * Updates fields on an application. If `pipeline_status` changes, a PipelineHistory entry is automatically appended (`from_status → to_status`).
 */
export const updateApplicationApiV1ApplicationsApplicationIdPatchMutation = (
  options?: Partial<
    Options<UpdateApplicationApiV1ApplicationsApplicationIdPatchData>
  >,
): UseMutationOptions<
  UpdateApplicationApiV1ApplicationsApplicationIdPatchResponse,
  UpdateApplicationApiV1ApplicationsApplicationIdPatchError,
  Options<UpdateApplicationApiV1ApplicationsApplicationIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateApplicationApiV1ApplicationsApplicationIdPatchResponse,
    UpdateApplicationApiV1ApplicationsApplicationIdPatchError,
    Options<UpdateApplicationApiV1ApplicationsApplicationIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await updateApplicationApiV1ApplicationsApplicationIdPatch({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

export const readContactsApiV1ContactsGetQueryKey = (
  options?: Options<ReadContactsApiV1ContactsGetData>,
) => createQueryKey("readContactsApiV1ContactsGet", options);

/**
 * Read Contacts
 * Read all contacts.
 */
export const readContactsApiV1ContactsGetOptions = (
  options?: Options<ReadContactsApiV1ContactsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readContactsApiV1ContactsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readContactsApiV1ContactsGetQueryKey(options),
  });
};

export const readContactsApiV1ContactsGetInfiniteQueryKey = (
  options?: Options<ReadContactsApiV1ContactsGetData>,
): QueryKey<Options<ReadContactsApiV1ContactsGetData>> =>
  createQueryKey("readContactsApiV1ContactsGet", options, true);

/**
 * Read Contacts
 * Read all contacts.
 */
export const readContactsApiV1ContactsGetInfiniteOptions = (
  options?: Options<ReadContactsApiV1ContactsGetData>,
) => {
  return infiniteQueryOptions<
    ReadContactsApiV1ContactsGetResponse,
    ReadContactsApiV1ContactsGetError,
    InfiniteData<ReadContactsApiV1ContactsGetResponse>,
    QueryKey<Options<ReadContactsApiV1ContactsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ReadContactsApiV1ContactsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ReadContactsApiV1ContactsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readContactsApiV1ContactsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: readContactsApiV1ContactsGetInfiniteQueryKey(options),
    },
  );
};

/**
 * Create Contact
 * Create a new contact.
 */
export const createContactApiV1ContactsPostMutation = (
  options?: Partial<Options<CreateContactApiV1ContactsPostData>>,
): UseMutationOptions<
  CreateContactApiV1ContactsPostResponse,
  CreateContactApiV1ContactsPostError,
  Options<CreateContactApiV1ContactsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateContactApiV1ContactsPostResponse,
    CreateContactApiV1ContactsPostError,
    Options<CreateContactApiV1ContactsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createContactApiV1ContactsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Contact
 * Delete a contact by ID.
 */
export const deleteContactApiV1ContactsContactIdDeleteMutation = (
  options?: Partial<Options<DeleteContactApiV1ContactsContactIdDeleteData>>,
): UseMutationOptions<
  DeleteContactApiV1ContactsContactIdDeleteResponse,
  DeleteContactApiV1ContactsContactIdDeleteError,
  Options<DeleteContactApiV1ContactsContactIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteContactApiV1ContactsContactIdDeleteResponse,
    DeleteContactApiV1ContactsContactIdDeleteError,
    Options<DeleteContactApiV1ContactsContactIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteContactApiV1ContactsContactIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const readContactApiV1ContactsContactIdGetQueryKey = (
  options: Options<ReadContactApiV1ContactsContactIdGetData>,
) => createQueryKey("readContactApiV1ContactsContactIdGet", options);

/**
 * Read Contact
 * Read a contact by ID.
 */
export const readContactApiV1ContactsContactIdGetOptions = (
  options: Options<ReadContactApiV1ContactsContactIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readContactApiV1ContactsContactIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readContactApiV1ContactsContactIdGetQueryKey(options),
  });
};

/**
 * Update Contact
 * Update a contact by ID.
 */
export const updateContactApiV1ContactsContactIdPatchMutation = (
  options?: Partial<Options<UpdateContactApiV1ContactsContactIdPatchData>>,
): UseMutationOptions<
  UpdateContactApiV1ContactsContactIdPatchResponse,
  UpdateContactApiV1ContactsContactIdPatchError,
  Options<UpdateContactApiV1ContactsContactIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateContactApiV1ContactsContactIdPatchResponse,
    UpdateContactApiV1ContactsContactIdPatchError,
    Options<UpdateContactApiV1ContactsContactIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateContactApiV1ContactsContactIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetQueryKey =
  (
    options: Options<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData>,
  ) =>
    createQueryKey(
      "listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGet",
      options,
    );

/**
 * List interviews for an application (nested)
 * Preferred way to fetch interviews scoped to a single application.
 *
 * **Use this when you already know the `application_id`.**
 *
 * Example:
 * ```
 * GET /api/v1/applications/42/interviews
 * ```
 * Query params: `limit`, `offset`.
 */
export const listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetOptions =
  (
    options: Options<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData>,
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            },
          );
        return data;
      },
      queryKey:
        listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetQueryKey(
          options,
        ),
    });
  };

export const listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetInfiniteQueryKey =
  (
    options: Options<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData>,
  ): QueryKey<
    Options<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData>
  > =>
    createQueryKey(
      "listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGet",
      options,
      true,
    );

/**
 * List interviews for an application (nested)
 * Preferred way to fetch interviews scoped to a single application.
 *
 * **Use this when you already know the `application_id`.**
 *
 * Example:
 * ```
 * GET /api/v1/applications/42/interviews
 * ```
 * Query params: `limit`, `offset`.
 */
export const listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetInfiniteOptions =
  (
    options: Options<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData>,
  ) => {
    return infiniteQueryOptions<
      ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponse,
      ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetError,
      InfiniteData<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponse>,
      QueryKey<
        Options<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData>
      >,
      | number
      | Pick<
          QueryKey<
            Options<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData>
          >[0],
          "body" | "headers" | "path" | "query"
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              Options<ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData>
            >[0],
            "body" | "headers" | "path" | "query"
          > =
            typeof pageParam === "object"
              ? pageParam
              : {
                  query: {
                    offset: pageParam,
                  },
                };
          const params = createInfiniteParams(queryKey, page);
          const { data } =
            await listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGet(
              {
                ...options,
                ...params,
                signal,
                throwOnError: true,
              },
            );
          return data;
        },
        queryKey:
          listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetInfiniteQueryKey(
            options,
          ),
      },
    );
  };

/**
 * Create an interview under an application (nested)
 * Creates an interview for a specific application.
 *
 * **Preferred over flat POST** because the parent is explicit in the path.
 *
 * Example body:
 * ```json
 * {
 * "scheduled_date": "2025-09-05T19:00:00Z",
 * "type": "recruiter",
 * "notes": "Recruiter screen"
 * }
 * ```
 */
export const createInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostMutation =
  (
    options?: Partial<
      Options<CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostData>
    >,
  ): UseMutationOptions<
    CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponse,
    CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostError,
    Options<CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponse,
      CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostError,
      Options<CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await createInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPost(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            },
          );
        return data;
      },
    };
    return mutationOptions;
  };

export const listInterviewsApiV1InterviewsGetQueryKey = (
  options?: Options<ListInterviewsApiV1InterviewsGetData>,
) => createQueryKey("listInterviewsApiV1InterviewsGet", options);

/**
 * List interviews (flat)
 * Lists interviews across applications.
 *
 * Optional filter: `?application_id=42`.
 *
 * **Tip:** If you’re already scoped to an application, prefer the nested endpoint.
 */
export const listInterviewsApiV1InterviewsGetOptions = (
  options?: Options<ListInterviewsApiV1InterviewsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listInterviewsApiV1InterviewsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listInterviewsApiV1InterviewsGetQueryKey(options),
  });
};

export const listInterviewsApiV1InterviewsGetInfiniteQueryKey = (
  options?: Options<ListInterviewsApiV1InterviewsGetData>,
): QueryKey<Options<ListInterviewsApiV1InterviewsGetData>> =>
  createQueryKey("listInterviewsApiV1InterviewsGet", options, true);

/**
 * List interviews (flat)
 * Lists interviews across applications.
 *
 * Optional filter: `?application_id=42`.
 *
 * **Tip:** If you’re already scoped to an application, prefer the nested endpoint.
 */
export const listInterviewsApiV1InterviewsGetInfiniteOptions = (
  options?: Options<ListInterviewsApiV1InterviewsGetData>,
) => {
  return infiniteQueryOptions<
    ListInterviewsApiV1InterviewsGetResponse,
    ListInterviewsApiV1InterviewsGetError,
    InfiniteData<ListInterviewsApiV1InterviewsGetResponse>,
    QueryKey<Options<ListInterviewsApiV1InterviewsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListInterviewsApiV1InterviewsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListInterviewsApiV1InterviewsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listInterviewsApiV1InterviewsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listInterviewsApiV1InterviewsGetInfiniteQueryKey(options),
    },
  );
};

/**
 * Create Interview Flat
 * Creates an interview when passing `application_id` in the request body.
 *
 * **Tip:** Prefer the nested endpoint when possible.**
 *
 * Example body:
 * ```json
 * {
 * "application_id": 42,
 * "scheduled_date": "2025-09-05T19:00:00Z",
 * "type": "recruiter",
 * "notes": "Recruiter screen"
 * }
 * ```
 */
export const createInterviewFlatApiV1InterviewsPostMutation = (
  options?: Partial<Options<CreateInterviewFlatApiV1InterviewsPostData>>,
): UseMutationOptions<
  CreateInterviewFlatApiV1InterviewsPostResponse,
  CreateInterviewFlatApiV1InterviewsPostError,
  Options<CreateInterviewFlatApiV1InterviewsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateInterviewFlatApiV1InterviewsPostResponse,
    CreateInterviewFlatApiV1InterviewsPostError,
    Options<CreateInterviewFlatApiV1InterviewsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createInterviewFlatApiV1InterviewsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an interview
 * Deletes an interview by ID.
 */
export const deleteInterviewApiV1InterviewsInterviewIdDeleteMutation = (
  options?: Partial<
    Options<DeleteInterviewApiV1InterviewsInterviewIdDeleteData>
  >,
): UseMutationOptions<
  DeleteInterviewApiV1InterviewsInterviewIdDeleteResponse,
  DeleteInterviewApiV1InterviewsInterviewIdDeleteError,
  Options<DeleteInterviewApiV1InterviewsInterviewIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteInterviewApiV1InterviewsInterviewIdDeleteResponse,
    DeleteInterviewApiV1InterviewsInterviewIdDeleteError,
    Options<DeleteInterviewApiV1InterviewsInterviewIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteInterviewApiV1InterviewsInterviewIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const readInterviewApiV1InterviewsInterviewIdGetQueryKey = (
  options: Options<ReadInterviewApiV1InterviewsInterviewIdGetData>,
) => createQueryKey("readInterviewApiV1InterviewsInterviewIdGet", options);

/**
 * Get an interview by ID
 * Fetch a single interview by ID.
 */
export const readInterviewApiV1InterviewsInterviewIdGetOptions = (
  options: Options<ReadInterviewApiV1InterviewsInterviewIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readInterviewApiV1InterviewsInterviewIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readInterviewApiV1InterviewsInterviewIdGetQueryKey(options),
  });
};

/**
 * Update an interview
 * Partial update. `scheduled_date` must be timezone-aware if provided. `application_id` reassignment is not supported here.
 */
export const updateInterviewApiV1InterviewsInterviewIdPatchMutation = (
  options?: Partial<
    Options<UpdateInterviewApiV1InterviewsInterviewIdPatchData>
  >,
): UseMutationOptions<
  UpdateInterviewApiV1InterviewsInterviewIdPatchResponse,
  UpdateInterviewApiV1InterviewsInterviewIdPatchError,
  Options<UpdateInterviewApiV1InterviewsInterviewIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateInterviewApiV1InterviewsInterviewIdPatchResponse,
    UpdateInterviewApiV1InterviewsInterviewIdPatchError,
    Options<UpdateInterviewApiV1InterviewsInterviewIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateInterviewApiV1InterviewsInterviewIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetQueryKey =
  (
    options: Options<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData>,
  ) =>
    createQueryKey(
      "listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGet",
      options,
    );

/**
 * List pipeline history for an application
 * Returns the pipeline history entries for an application, ordered by `changed_at` descending (most recent first).
 */
export const listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetOptions =
  (
    options: Options<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData>,
  ) => {
    return queryOptions({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            },
          );
        return data;
      },
      queryKey:
        listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetQueryKey(
          options,
        ),
    });
  };

export const listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetInfiniteQueryKey =
  (
    options: Options<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData>,
  ): QueryKey<
    Options<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData>
  > =>
    createQueryKey(
      "listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGet",
      options,
      true,
    );

/**
 * List pipeline history for an application
 * Returns the pipeline history entries for an application, ordered by `changed_at` descending (most recent first).
 */
export const listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetInfiniteOptions =
  (
    options: Options<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData>,
  ) => {
    return infiniteQueryOptions<
      ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponse,
      ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetError,
      InfiniteData<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponse>,
      QueryKey<
        Options<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData>
      >,
      | number
      | Pick<
          QueryKey<
            Options<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData>
          >[0],
          "body" | "headers" | "path" | "query"
        >
    >(
      // @ts-ignore
      {
        queryFn: async ({ pageParam, queryKey, signal }) => {
          // @ts-ignore
          const page: Pick<
            QueryKey<
              Options<ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData>
            >[0],
            "body" | "headers" | "path" | "query"
          > =
            typeof pageParam === "object"
              ? pageParam
              : {
                  query: {
                    offset: pageParam,
                  },
                };
          const params = createInfiniteParams(queryKey, page);
          const { data } =
            await listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGet(
              {
                ...options,
                ...params,
                signal,
                throwOnError: true,
              },
            );
          return data;
        },
        queryKey:
          listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetInfiniteQueryKey(
            options,
          ),
      },
    );
  };

/**
 * Create pipeline history under an application
 * Creates a new pipeline history entry for the specified application. `from_status` may be omitted for initial transitions. Use this nested endpoint for typical client flows.
 */
export const createPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostMutation =
  (
    options?: Partial<
      Options<CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostData>
    >,
  ): UseMutationOptions<
    CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponse,
    CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostError,
    Options<CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponse,
      CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostError,
      Options<CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await createPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPost(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            },
          );
        return data;
      },
    };
    return mutationOptions;
  };

export const readPipelineHistoriesApiV1PipelineHistoryGetQueryKey = (
  options?: Options<ReadPipelineHistoriesApiV1PipelineHistoryGetData>,
) => createQueryKey("readPipelineHistoriesApiV1PipelineHistoryGet", options);

/**
 * List pipeline history (optionally filter by application_id)
 * Returns pipeline history entries across all applications. Use `application_id` query param to filter. Results are ordered by `changed_at` descending (most recent first).
 */
export const readPipelineHistoriesApiV1PipelineHistoryGetOptions = (
  options?: Options<ReadPipelineHistoriesApiV1PipelineHistoryGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readPipelineHistoriesApiV1PipelineHistoryGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: readPipelineHistoriesApiV1PipelineHistoryGetQueryKey(options),
  });
};

export const readPipelineHistoriesApiV1PipelineHistoryGetInfiniteQueryKey = (
  options?: Options<ReadPipelineHistoriesApiV1PipelineHistoryGetData>,
): QueryKey<Options<ReadPipelineHistoriesApiV1PipelineHistoryGetData>> =>
  createQueryKey("readPipelineHistoriesApiV1PipelineHistoryGet", options, true);

/**
 * List pipeline history (optionally filter by application_id)
 * Returns pipeline history entries across all applications. Use `application_id` query param to filter. Results are ordered by `changed_at` descending (most recent first).
 */
export const readPipelineHistoriesApiV1PipelineHistoryGetInfiniteOptions = (
  options?: Options<ReadPipelineHistoriesApiV1PipelineHistoryGetData>,
) => {
  return infiniteQueryOptions<
    ReadPipelineHistoriesApiV1PipelineHistoryGetResponse,
    ReadPipelineHistoriesApiV1PipelineHistoryGetError,
    InfiniteData<ReadPipelineHistoriesApiV1PipelineHistoryGetResponse>,
    QueryKey<Options<ReadPipelineHistoriesApiV1PipelineHistoryGetData>>,
    | number
    | Pick<
        QueryKey<Options<ReadPipelineHistoriesApiV1PipelineHistoryGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<
            Options<ReadPipelineHistoriesApiV1PipelineHistoryGetData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readPipelineHistoriesApiV1PipelineHistoryGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        readPipelineHistoriesApiV1PipelineHistoryGetInfiniteQueryKey(options),
    },
  );
};

/**
 * Create pipeline history (flat)
 * Creates a pipeline history entry using a request body with `application_id`. If you already know the application context, prefer the nested POST.
 */
export const createPipelineHistoryApiV1PipelineHistoryPostMutation = (
  options?: Partial<Options<CreatePipelineHistoryApiV1PipelineHistoryPostData>>,
): UseMutationOptions<
  CreatePipelineHistoryApiV1PipelineHistoryPostResponse,
  CreatePipelineHistoryApiV1PipelineHistoryPostError,
  Options<CreatePipelineHistoryApiV1PipelineHistoryPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreatePipelineHistoryApiV1PipelineHistoryPostResponse,
    CreatePipelineHistoryApiV1PipelineHistoryPostError,
    Options<CreatePipelineHistoryApiV1PipelineHistoryPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createPipelineHistoryApiV1PipelineHistoryPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a pipeline history record
 * Delete a pipeline history record by id.
 */
export const deletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteMutation =
  (
    options?: Partial<
      Options<DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteData>
    >,
  ): UseMutationOptions<
    DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponse,
    DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteError,
    Options<DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteData>
  > => {
    const mutationOptions: UseMutationOptions<
      DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponse,
      DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteError,
      Options<DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await deletePipelineHistoryApiV1PipelineHistoryHistoryIdDelete({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

export const readPipelineHistoryApiV1PipelineHistoryHistoryIdGetQueryKey = (
  options: Options<ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetData>,
) =>
  createQueryKey(
    "readPipelineHistoryApiV1PipelineHistoryHistoryIdGet",
    options,
  );

/**
 * Get a pipeline history record by id
 * Get a pipeline history record by id.
 */
export const readPipelineHistoryApiV1PipelineHistoryHistoryIdGetOptions = (
  options: Options<ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await readPipelineHistoryApiV1PipelineHistoryHistoryIdGet({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
      return data;
    },
    queryKey:
      readPipelineHistoryApiV1PipelineHistoryHistoryIdGetQueryKey(options),
  });
};

/**
 * Update a pipeline history note
 * Only the `note` field may be updated. Status fields are ignored.
 */
export const updatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchMutation = (
  options?: Partial<
    Options<UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchData>
  >,
): UseMutationOptions<
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponse,
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchError,
  Options<UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponse,
    UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchError,
    Options<UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await updatePipelineHistoryApiV1PipelineHistoryHistoryIdPatch({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};
