[mypy]
python_version = 3.13
ignore_missing_imports = True
warn_unused_ignores = True
strict_optional = True

# Helpful plugins if you later add typed ORM / pydantic models
plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin

# Suppress SQLite ORM models oddities
[mypy-app.models.*]
ignore_errors = True

# Pydantic Update schemas & computed_field decorator oddities
[mypy-app.schemas.*]
disable_error_code = assignment, prop-decorator
