// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  HealthCheckHealthCheckGetData,
  HealthCheckHealthCheckGetResponses,
  ReadApplicationsApiV1ApplicationsGetData,
  ReadApplicationsApiV1ApplicationsGetResponses,
  ReadApplicationsApiV1ApplicationsGetErrors,
  CreateApplicationApiV1ApplicationsPostData,
  CreateApplicationApiV1ApplicationsPostResponses,
  CreateApplicationApiV1ApplicationsPostErrors,
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteData,
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponses,
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteErrors,
  ReadApplicationApiV1ApplicationsApplicationIdGetData,
  ReadApplicationApiV1ApplicationsApplicationIdGetResponses,
  ReadApplicationApiV1ApplicationsApplicationIdGetErrors,
  UpdateApplicationApiV1ApplicationsApplicationIdPatchData,
  UpdateApplicationApiV1ApplicationsApplicationIdPatchResponses,
  UpdateApplicationApiV1ApplicationsApplicationIdPatchErrors,
  ReadContactsApiV1ContactsGetData,
  ReadContactsApiV1ContactsGetResponses,
  ReadContactsApiV1ContactsGetErrors,
  CreateContactApiV1ContactsPostData,
  CreateContactApiV1ContactsPostResponses,
  CreateContactApiV1ContactsPostErrors,
  DeleteContactApiV1ContactsContactIdDeleteData,
  DeleteContactApiV1ContactsContactIdDeleteResponses,
  DeleteContactApiV1ContactsContactIdDeleteErrors,
  ReadContactApiV1ContactsContactIdGetData,
  ReadContactApiV1ContactsContactIdGetResponses,
  ReadContactApiV1ContactsContactIdGetErrors,
  UpdateContactApiV1ContactsContactIdPatchData,
  UpdateContactApiV1ContactsContactIdPatchResponses,
  UpdateContactApiV1ContactsContactIdPatchErrors,
  ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData,
  ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponses,
  ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetErrors,
  CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostData,
  CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponses,
  CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostErrors,
  ListInterviewsApiV1InterviewsGetData,
  ListInterviewsApiV1InterviewsGetResponses,
  ListInterviewsApiV1InterviewsGetErrors,
  CreateInterviewFlatApiV1InterviewsPostData,
  CreateInterviewFlatApiV1InterviewsPostResponses,
  CreateInterviewFlatApiV1InterviewsPostErrors,
  DeleteInterviewApiV1InterviewsInterviewIdDeleteData,
  DeleteInterviewApiV1InterviewsInterviewIdDeleteResponses,
  DeleteInterviewApiV1InterviewsInterviewIdDeleteErrors,
  ReadInterviewApiV1InterviewsInterviewIdGetData,
  ReadInterviewApiV1InterviewsInterviewIdGetResponses,
  ReadInterviewApiV1InterviewsInterviewIdGetErrors,
  UpdateInterviewApiV1InterviewsInterviewIdPatchData,
  UpdateInterviewApiV1InterviewsInterviewIdPatchResponses,
  UpdateInterviewApiV1InterviewsInterviewIdPatchErrors,
  ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData,
  ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponses,
  ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetErrors,
  CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostData,
  CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponses,
  CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostErrors,
  ReadPipelineHistoriesApiV1PipelineHistoryGetData,
  ReadPipelineHistoriesApiV1PipelineHistoryGetResponses,
  ReadPipelineHistoriesApiV1PipelineHistoryGetErrors,
  CreatePipelineHistoryApiV1PipelineHistoryPostData,
  CreatePipelineHistoryApiV1PipelineHistoryPostResponses,
  CreatePipelineHistoryApiV1PipelineHistoryPostErrors,
  DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteData,
  DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponses,
  DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteErrors,
  ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetData,
  ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetResponses,
  ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetErrors,
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchData,
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponses,
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchErrors,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 * Stubbed health check for testing.
 */
export const healthCheckHealthCheckGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthCheckGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    HealthCheckHealthCheckGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health-check",
    ...options,
  });
};

/**
 * List applications
 * Returns applications with interviews, contacts, and pipeline history preloaded.
 */
export const readApplicationsApiV1ApplicationsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReadApplicationsApiV1ApplicationsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadApplicationsApiV1ApplicationsGetResponses,
    ReadApplicationsApiV1ApplicationsGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/applications/",
    ...options,
  });
};

/**
 * Create an application
 * Creates a new application and automatically logs an initial pipeline history entry (`None → pipeline_status`).
 */
export const createApplicationApiV1ApplicationsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateApplicationApiV1ApplicationsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateApplicationApiV1ApplicationsPostResponses,
    CreateApplicationApiV1ApplicationsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/applications/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete an application
 * Deletes the application; associated PipelineHistory, Interviews, and links are removed via cascade.
 */
export const deleteApplicationApiV1ApplicationsApplicationIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteApplicationApiV1ApplicationsApplicationIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponses,
    DeleteApplicationApiV1ApplicationsApplicationIdDeleteErrors,
    ThrowOnError
  >({
    url: "/api/v1/applications/{application_id}",
    ...options,
  });
};

/**
 * Get an application by id
 * Returns one application with interviews, contacts, and pipeline history.
 */
export const readApplicationApiV1ApplicationsApplicationIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadApplicationApiV1ApplicationsApplicationIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    ReadApplicationApiV1ApplicationsApplicationIdGetResponses,
    ReadApplicationApiV1ApplicationsApplicationIdGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/applications/{application_id}",
    ...options,
  });
};

/**
 * Update an application
 * Updates fields on an application. If `pipeline_status` changes, a PipelineHistory entry is automatically appended (`from_status → to_status`).
 */
export const updateApplicationApiV1ApplicationsApplicationIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateApplicationApiV1ApplicationsApplicationIdPatchData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateApplicationApiV1ApplicationsApplicationIdPatchResponses,
    UpdateApplicationApiV1ApplicationsApplicationIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/applications/{application_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read all contacts.
 * Read all contacts with optional filtering by name, company, or linked application ID.
 *
 * Example:
 * ```
 * GET /api/v1/contacts?name=John&company=Acme&application_id=42&limit=20&offset=0
 * ```
 * Query params: `name`, `company`, `application_id`, `limit`, `offset`.
 */
export const readContactsApiV1ContactsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReadContactsApiV1ContactsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadContactsApiV1ContactsGetResponses,
    ReadContactsApiV1ContactsGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/contacts/",
    ...options,
  });
};

/**
 * Create a new contact.
 * Create a new contact, optionally linking to existing applications.
 */
export const createContactApiV1ContactsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateContactApiV1ContactsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateContactApiV1ContactsPostResponses,
    CreateContactApiV1ContactsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/contacts/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a contact by ID.
 * Delete a contact by its ID.
 */
export const deleteContactApiV1ContactsContactIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteContactApiV1ContactsContactIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteContactApiV1ContactsContactIdDeleteResponses,
    DeleteContactApiV1ContactsContactIdDeleteErrors,
    ThrowOnError
  >({
    url: "/api/v1/contacts/{contact_id}",
    ...options,
  });
};

/**
 * Read a contact by ID.
 * Read a contact by its unique ID.
 */
export const readContactApiV1ContactsContactIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadContactApiV1ContactsContactIdGetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ReadContactApiV1ContactsContactIdGetResponses,
    ReadContactApiV1ContactsContactIdGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/contacts/{contact_id}",
    ...options,
  });
};

/**
 * Update a contact by ID.
 * Update a contact by its ID. You can also manage linked applications using `application_ids_add` and `application_ids_remove` fields to add or remove links.
 */
export const updateContactApiV1ContactsContactIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateContactApiV1ContactsContactIdPatchData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateContactApiV1ContactsContactIdPatchResponses,
    UpdateContactApiV1ContactsContactIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/contacts/{contact_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List interviews for an application (nested)
 * Preferred way to fetch interviews scoped to a single application.
 *
 * **Use this when you already know the `application_id`.**
 *
 * Example:
 * ```
 * GET /api/v1/applications/42/interviews
 * ```
 * Query params: `limit`, `offset`.
 */
export const listInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? _heyApiClient).get<
      ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponses,
      ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/applications/{application_id}/interviews",
      ...options,
    });
  };

/**
 * Create an interview under an application (nested)
 * Creates an interview for a specific application.
 *
 * **Preferred over flat POST** because the parent is explicit in the path.
 *
 * Example body:
 * ```json
 * {
 * "scheduled_date": "2025-09-05T19:00:00Z",
 * "type": "recruiter",
 * "notes": "Recruiter screen"
 * }
 * ```
 */
export const createInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? _heyApiClient).post<
      CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponses,
      CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/applications/{application_id}/interviews",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  };

/**
 * List interviews (flat)
 * Lists interviews across applications.
 *
 * Optional filter: `?application_id=42`.
 *
 * **Tip:** If you’re already scoped to an application, prefer the nested endpoint.
 */
export const listInterviewsApiV1InterviewsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListInterviewsApiV1InterviewsGetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListInterviewsApiV1InterviewsGetResponses,
    ListInterviewsApiV1InterviewsGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/interviews",
    ...options,
  });
};

/**
 * Create Interview Flat
 * Creates an interview when passing `application_id` in the request body.
 *
 * **Tip:** Prefer the nested endpoint when possible.**
 *
 * Example body:
 * ```json
 * {
 * "application_id": 42,
 * "scheduled_date": "2025-09-05T19:00:00Z",
 * "type": "recruiter",
 * "notes": "Recruiter screen"
 * }
 * ```
 */
export const createInterviewFlatApiV1InterviewsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateInterviewFlatApiV1InterviewsPostData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateInterviewFlatApiV1InterviewsPostResponses,
    CreateInterviewFlatApiV1InterviewsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/interviews",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete an interview
 * Deletes an interview by ID.
 */
export const deleteInterviewApiV1InterviewsInterviewIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteInterviewApiV1InterviewsInterviewIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteInterviewApiV1InterviewsInterviewIdDeleteResponses,
    DeleteInterviewApiV1InterviewsInterviewIdDeleteErrors,
    ThrowOnError
  >({
    url: "/api/v1/interviews/{interview_id}",
    ...options,
  });
};

/**
 * Get an interview by ID
 * Fetch a single interview by ID.
 */
export const readInterviewApiV1InterviewsInterviewIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadInterviewApiV1InterviewsInterviewIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    ReadInterviewApiV1InterviewsInterviewIdGetResponses,
    ReadInterviewApiV1InterviewsInterviewIdGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/interviews/{interview_id}",
    ...options,
  });
};

/**
 * Update an interview
 * Partial update. `scheduled_date` must be timezone-aware if provided. `application_id` reassignment is not supported here.
 */
export const updateInterviewApiV1InterviewsInterviewIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateInterviewApiV1InterviewsInterviewIdPatchData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateInterviewApiV1InterviewsInterviewIdPatchResponses,
    UpdateInterviewApiV1InterviewsInterviewIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/interviews/{interview_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List pipeline history for an application
 * Returns the pipeline history entries for an application, ordered by `changed_at` descending (most recent first).
 */
export const listPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? _heyApiClient).get<
      ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponses,
      ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/applications/{application_id}/pipeline-history",
      ...options,
    });
  };

/**
 * Create pipeline history under an application
 * Creates a new pipeline history entry for the specified application. `from_status` may be omitted for initial transitions. Use this nested endpoint for typical client flows.
 */
export const createPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPost =
  <ThrowOnError extends boolean = false>(
    options: Options<
      CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostData,
      ThrowOnError
    >,
  ) => {
    return (options.client ?? _heyApiClient).post<
      CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponses,
      CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostErrors,
      ThrowOnError
    >({
      url: "/api/v1/applications/{application_id}/pipeline-history",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  };

/**
 * List pipeline history (optionally filter by application_id)
 * Returns pipeline history entries across all applications. Use `application_id` query param to filter. Results are ordered by `changed_at` descending (most recent first).
 */
export const readPipelineHistoriesApiV1PipelineHistoryGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ReadPipelineHistoriesApiV1PipelineHistoryGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? _heyApiClient).get<
    ReadPipelineHistoriesApiV1PipelineHistoryGetResponses,
    ReadPipelineHistoriesApiV1PipelineHistoryGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/pipeline-history",
    ...options,
  });
};

/**
 * Create pipeline history (flat)
 * Creates a pipeline history entry using a request body with `application_id`. If you already know the application context, prefer the nested POST.
 */
export const createPipelineHistoryApiV1PipelineHistoryPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreatePipelineHistoryApiV1PipelineHistoryPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    CreatePipelineHistoryApiV1PipelineHistoryPostResponses,
    CreatePipelineHistoryApiV1PipelineHistoryPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/pipeline-history",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete a pipeline history record
 * Delete a pipeline history record by id.
 */
export const deletePipelineHistoryApiV1PipelineHistoryHistoryIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponses,
    DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteErrors,
    ThrowOnError
  >({
    url: "/api/v1/pipeline-history/{history_id}",
    ...options,
  });
};

/**
 * Get a pipeline history record by id
 * Get a pipeline history record by id.
 */
export const readPipelineHistoryApiV1PipelineHistoryHistoryIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetResponses,
    ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/pipeline-history/{history_id}",
    ...options,
  });
};

/**
 * Update a pipeline history note
 * Only the `note` field may be updated. Status fields are ignored.
 */
export const updatePipelineHistoryApiV1PipelineHistoryHistoryIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchData,
    ThrowOnError
  >,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponses,
    UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/pipeline-history/{history_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
