// This file is auto-generated by @hey-api/openapi-ts

/**
 * ApplicationCreate
 * Schema for creating a new application.
 */
export type ApplicationCreate = {
  /**
   * Date Applied
   */
  date_applied: string;
  /**
   * Company
   */
  company: string;
  /**
   * Recruiting Agency
   */
  recruiting_agency?: string | null;
  /**
   * Role
   */
  role: string;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Salary Min
   */
  salary_min?: number | null;
  /**
   * Salary Max
   */
  salary_max?: number | null;
  /**
   * Salary Target
   */
  salary_target?: number | null;
  job_location: JobLocation;
  pipeline_status?: PipelineStatus;
  /**
   * Next Follow Up At
   */
  next_follow_up_at?: string | null;
  resolution_status?: ResolutionStatus;
  /**
   * Resolution Date
   */
  resolution_date?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * ApplicationRead
 * Represents an application entity with its associated attributes.
 */
export type ApplicationRead = {
  /**
   * Date Applied
   */
  date_applied: string;
  /**
   * Company
   */
  company: string;
  /**
   * Recruiting Agency
   */
  recruiting_agency?: string | null;
  /**
   * Role
   */
  role: string;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Salary Min
   */
  salary_min?: number | null;
  /**
   * Salary Max
   */
  salary_max?: number | null;
  /**
   * Salary Target
   */
  salary_target?: number | null;
  job_location: JobLocation;
  pipeline_status?: PipelineStatus;
  /**
   * Next Follow Up At
   */
  next_follow_up_at?: string | null;
  resolution_status?: ResolutionStatus;
  /**
   * Resolution Date
   */
  resolution_date?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at?: string | null;
  /**
   * Interviews
   */
  interviews?: Array<InterviewRead>;
  /**
   * Contacts
   */
  contacts?: Array<ContactRead>;
  /**
   * Pipeline Histories
   */
  pipeline_histories?: Array<PipelineHistoryRead>;
};

/**
 * ApplicationUpdate
 * Schema for updating an existing application, all fields optional.
 */
export type ApplicationUpdate = {
  /**
   * Date Applied
   */
  date_applied?: string | null;
  /**
   * Company
   */
  company?: string | null;
  /**
   * Recruiting Agency
   */
  recruiting_agency?: string | null;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Salary Min
   */
  salary_min?: number | null;
  /**
   * Salary Max
   */
  salary_max?: number | null;
  /**
   * Salary Target
   */
  salary_target?: number | null;
  job_location?: JobLocation | null;
  pipeline_status?: PipelineStatus | null;
  /**
   * Next Follow Up At
   */
  next_follow_up_at?: string | null;
  resolution_status?: ResolutionStatus | null;
  /**
   * Resolution Date
   */
  resolution_date?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * ContactCreate
 * Schema for creating a new contact.
 */
export type ContactCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Company
   */
  company: string;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Application Ids
   */
  application_ids?: Array<number>;
};

/**
 * ContactRead
 * Represents a contact entity with its associated attributes. Phone will always return RFC 3966 format.
 */
export type ContactRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Company
   */
  company: string;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at?: string | null;
  /**
   * Application Ids
   * Serializes applications ids.
   */
  readonly application_ids: Array<number>;
};

/**
 * ContactUpdate
 * Schema for updating an existing contact. Phone accepts E.164 and RFC 3966 formats.
 */
export type ContactUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Company
   */
  company?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Application Ids Add
   */
  application_ids_add?: Array<number> | null;
  /**
   * Application Ids Remove
   */
  application_ids_remove?: Array<number> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * InterviewCreate
 * Schema for creating a new Interview. For nested POST; application_id comes from the path.
 */
export type InterviewCreate = {
  /**
   * Scheduled Date
   * Timezone-aware datetime(ISO 8601, e.g. 2025-09-05T19:00:00Z)
   */
  scheduled_date: string;
  type: InterviewType;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * InterviewCreateFlat
 * Schema for creating a new Interview (flat).
 */
export type InterviewCreateFlat = {
  /**
   * Scheduled Date
   * Timezone-aware datetime(ISO 8601, e.g. 2025-09-05T19:00:00Z)
   */
  scheduled_date: string;
  type: InterviewType;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Application Id
   */
  application_id?: number | null;
};

/**
 * InterviewRead
 * Represents a Interview entity with its associated attributes.
 */
export type InterviewRead = {
  /**
   * Scheduled Date
   * Timezone-aware datetime(ISO 8601, e.g. 2025-09-05T19:00:00Z)
   */
  scheduled_date: string;
  type: InterviewType;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Application Id
   */
  application_id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at?: string | null;
};

/**
 * InterviewType
 * Type/category of an interview event in the pipeline.
 */
export type InterviewType =
  | "behavioral"
  | "final"
  | "hiring_manager"
  | "offer"
  | "offer_negotiation"
  | "recruiter"
  | "technical";

/**
 * InterviewUpdate
 * Schema for updating a new Interview
 */
export type InterviewUpdate = {
  /**
   * Scheduled Date
   */
  scheduled_date?: string | null;
  type?: InterviewType | null;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Application Id
   */
  application_id?: number | null;
};

/**
 * JobLocation
 * Location modality for the job (as stated in the JD or negotiated).
 */
export type JobLocation = "hybrid" | "onsite" | "remote";

/**
 * PipelineHistoryCreate
 * Schema for creating a new pipeline history record.
 * For nested POST; application_id comes from the path.
 */
export type PipelineHistoryCreate = {
  /**
   * Previous status (nullable for first transition).
   */
  from_status?: PipelineStatus | null;
  /**
   * Target status the application moved into.
   */
  to_status: PipelineStatus;
  /**
   * Note
   * Optional human note describing the change.
   */
  note?: string | null;
};

/**
 * PipelineHistoryCreateFlat
 * Schema for creating a new pipeline history record (flat).
 */
export type PipelineHistoryCreateFlat = {
  /**
   * Previous status (nullable for first transition).
   */
  from_status?: PipelineStatus | null;
  /**
   * Target status the application moved into.
   */
  to_status: PipelineStatus;
  /**
   * Note
   * Optional human note describing the change.
   */
  note?: string | null;
  /**
   * Application Id
   * Application id to attach this history to.
   */
  application_id: number;
};

/**
 * PipelineHistoryRead
 * Schema for pipeline history with all fields.
 */
export type PipelineHistoryRead = {
  /**
   * Previous status (nullable for first transition).
   */
  from_status?: PipelineStatus | null;
  /**
   * Target status the application moved into.
   */
  to_status: PipelineStatus;
  /**
   * Note
   * Optional human note describing the change.
   */
  note?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Application Id
   */
  application_id: number;
  /**
   * Changed At
   */
  changed_at: string;
};

/**
 * PipelineHistoryUpdate
 * Schema for updating a pipeline history record.
 *
 * Only `note` may be updated. Attempts to change status fields are ignored by the router.
 */
export type PipelineHistoryUpdate = {
  /**
   * Note
   * New note. If omitted, note remains unchanged.
   */
  note?: string | null;
};

/**
 * PipelineStatus
 * Pipeline status for an application (high-level stage).
 */
export type PipelineStatus =
  | "applied"
  | "final_round"
  | "offered"
  | "resolved"
  | "stage_1"
  | "stage_2"
  | "stage_3_plus"
  | "will_apply";

/**
 * ResolutionStatus
 * Outcome state for a resolved application.
 */
export type ResolutionStatus =
  | "ghosted"
  | "offer_accepted"
  | "offer_declined"
  | "ongoing"
  | "on_hold"
  | "rejected";

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * ContactRead
 * Represents a contact entity with its associated attributes. Phone will always return RFC 3966 format.
 */
export type ContactReadWritable = {
  /**
   * Name
   */
  name: string;
  /**
   * Company
   */
  company: string;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Title
   */
  title?: string | null;
  /**
   * Url
   */
  url?: string | null;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Notes
   */
  notes?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at?: string | null;
};

export type HealthCheckHealthCheckGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health-check";
};

export type HealthCheckHealthCheckGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadApplicationsApiV1ApplicationsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/applications/";
};

export type ReadApplicationsApiV1ApplicationsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadApplicationsApiV1ApplicationsGetError =
  ReadApplicationsApiV1ApplicationsGetErrors[keyof ReadApplicationsApiV1ApplicationsGetErrors];

export type ReadApplicationsApiV1ApplicationsGetResponses = {
  /**
   * Response Read Applications Api V1 Applications  Get
   * Successful Response
   */
  200: Array<ApplicationRead>;
};

export type ReadApplicationsApiV1ApplicationsGetResponse =
  ReadApplicationsApiV1ApplicationsGetResponses[keyof ReadApplicationsApiV1ApplicationsGetResponses];

export type CreateApplicationApiV1ApplicationsPostData = {
  body: ApplicationCreate;
  path?: never;
  query?: never;
  url: "/api/v1/applications/";
};

export type CreateApplicationApiV1ApplicationsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateApplicationApiV1ApplicationsPostError =
  CreateApplicationApiV1ApplicationsPostErrors[keyof CreateApplicationApiV1ApplicationsPostErrors];

export type CreateApplicationApiV1ApplicationsPostResponses = {
  /**
   * Successful Response
   */
  201: ApplicationRead;
};

export type CreateApplicationApiV1ApplicationsPostResponse =
  CreateApplicationApiV1ApplicationsPostResponses[keyof CreateApplicationApiV1ApplicationsPostResponses];

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteData = {
  body?: never;
  path: {
    /**
     * Application Id
     */
    application_id: number;
  };
  query?: never;
  url: "/api/v1/applications/{application_id}";
};

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteError =
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteErrors[keyof DeleteApplicationApiV1ApplicationsApplicationIdDeleteErrors];

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponse =
  DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponses[keyof DeleteApplicationApiV1ApplicationsApplicationIdDeleteResponses];

export type ReadApplicationApiV1ApplicationsApplicationIdGetData = {
  body?: never;
  path: {
    /**
     * Application Id
     */
    application_id: number;
  };
  query?: never;
  url: "/api/v1/applications/{application_id}";
};

export type ReadApplicationApiV1ApplicationsApplicationIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadApplicationApiV1ApplicationsApplicationIdGetError =
  ReadApplicationApiV1ApplicationsApplicationIdGetErrors[keyof ReadApplicationApiV1ApplicationsApplicationIdGetErrors];

export type ReadApplicationApiV1ApplicationsApplicationIdGetResponses = {
  /**
   * Successful Response
   */
  200: ApplicationRead;
};

export type ReadApplicationApiV1ApplicationsApplicationIdGetResponse =
  ReadApplicationApiV1ApplicationsApplicationIdGetResponses[keyof ReadApplicationApiV1ApplicationsApplicationIdGetResponses];

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchData = {
  body: ApplicationUpdate;
  path: {
    /**
     * Application Id
     */
    application_id: number;
  };
  query?: never;
  url: "/api/v1/applications/{application_id}";
};

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchError =
  UpdateApplicationApiV1ApplicationsApplicationIdPatchErrors[keyof UpdateApplicationApiV1ApplicationsApplicationIdPatchErrors];

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ApplicationRead;
};

export type UpdateApplicationApiV1ApplicationsApplicationIdPatchResponse =
  UpdateApplicationApiV1ApplicationsApplicationIdPatchResponses[keyof UpdateApplicationApiV1ApplicationsApplicationIdPatchResponses];

export type ReadContactsApiV1ContactsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Company
     */
    company?: string | null;
    /**
     * Application Id
     */
    application_id?: number | null;
  };
  url: "/api/v1/contacts/";
};

export type ReadContactsApiV1ContactsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadContactsApiV1ContactsGetError =
  ReadContactsApiV1ContactsGetErrors[keyof ReadContactsApiV1ContactsGetErrors];

export type ReadContactsApiV1ContactsGetResponses = {
  /**
   * Response Read Contacts Api V1 Contacts  Get
   * Successful Response
   */
  200: Array<ContactRead>;
};

export type ReadContactsApiV1ContactsGetResponse =
  ReadContactsApiV1ContactsGetResponses[keyof ReadContactsApiV1ContactsGetResponses];

export type CreateContactApiV1ContactsPostData = {
  body: ContactCreate;
  path?: never;
  query?: never;
  url: "/api/v1/contacts/";
};

export type CreateContactApiV1ContactsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateContactApiV1ContactsPostError =
  CreateContactApiV1ContactsPostErrors[keyof CreateContactApiV1ContactsPostErrors];

export type CreateContactApiV1ContactsPostResponses = {
  /**
   * Successful Response
   */
  201: ContactRead;
};

export type CreateContactApiV1ContactsPostResponse =
  CreateContactApiV1ContactsPostResponses[keyof CreateContactApiV1ContactsPostResponses];

export type DeleteContactApiV1ContactsContactIdDeleteData = {
  body?: never;
  path: {
    /**
     * Contact Id
     */
    contact_id: number;
  };
  query?: never;
  url: "/api/v1/contacts/{contact_id}";
};

export type DeleteContactApiV1ContactsContactIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteContactApiV1ContactsContactIdDeleteError =
  DeleteContactApiV1ContactsContactIdDeleteErrors[keyof DeleteContactApiV1ContactsContactIdDeleteErrors];

export type DeleteContactApiV1ContactsContactIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteContactApiV1ContactsContactIdDeleteResponse =
  DeleteContactApiV1ContactsContactIdDeleteResponses[keyof DeleteContactApiV1ContactsContactIdDeleteResponses];

export type ReadContactApiV1ContactsContactIdGetData = {
  body?: never;
  path: {
    /**
     * Contact Id
     */
    contact_id: number;
  };
  query?: never;
  url: "/api/v1/contacts/{contact_id}";
};

export type ReadContactApiV1ContactsContactIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadContactApiV1ContactsContactIdGetError =
  ReadContactApiV1ContactsContactIdGetErrors[keyof ReadContactApiV1ContactsContactIdGetErrors];

export type ReadContactApiV1ContactsContactIdGetResponses = {
  /**
   * Successful Response
   */
  200: ContactRead;
};

export type ReadContactApiV1ContactsContactIdGetResponse =
  ReadContactApiV1ContactsContactIdGetResponses[keyof ReadContactApiV1ContactsContactIdGetResponses];

export type UpdateContactApiV1ContactsContactIdPatchData = {
  body: ContactUpdate;
  path: {
    /**
     * Contact Id
     */
    contact_id: number;
  };
  query?: never;
  url: "/api/v1/contacts/{contact_id}";
};

export type UpdateContactApiV1ContactsContactIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateContactApiV1ContactsContactIdPatchError =
  UpdateContactApiV1ContactsContactIdPatchErrors[keyof UpdateContactApiV1ContactsContactIdPatchErrors];

export type UpdateContactApiV1ContactsContactIdPatchResponses = {
  /**
   * Successful Response
   */
  200: ContactRead;
};

export type UpdateContactApiV1ContactsContactIdPatchResponse =
  UpdateContactApiV1ContactsContactIdPatchResponses[keyof UpdateContactApiV1ContactsContactIdPatchResponses];

export type ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetData =
  {
    body?: never;
    path: {
      /**
       * Application Id
       */
      application_id: number;
    };
    query?: {
      /**
       * Limit
       */
      limit?: number;
      /**
       * Offset
       */
      offset?: number;
    };
    url: "/api/v1/applications/{application_id}/interviews";
  };

export type ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetError =
  ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetErrors[keyof ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetErrors];

export type ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponses =
  {
    /**
     * Response List Interviews For Application Api V1 Applications  Application Id  Interviews Get
     * Successful Response
     */
    200: Array<InterviewRead>;
  };

export type ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponse =
  ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponses[keyof ListInterviewsForApplicationApiV1ApplicationsApplicationIdInterviewsGetResponses];

export type CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostData =
  {
    body: InterviewCreate;
    path: {
      /**
       * Application Id
       */
      application_id: number;
    };
    query?: never;
    url: "/api/v1/applications/{application_id}/interviews";
  };

export type CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostError =
  CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostErrors[keyof CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostErrors];

export type CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponses =
  {
    /**
     * Successful Response
     */
    201: InterviewRead;
  };

export type CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponse =
  CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponses[keyof CreateInterviewForApplicationApiV1ApplicationsApplicationIdInterviewsPostResponses];

export type ListInterviewsApiV1InterviewsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Application Id
     */
    application_id?: number | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/interviews";
};

export type ListInterviewsApiV1InterviewsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListInterviewsApiV1InterviewsGetError =
  ListInterviewsApiV1InterviewsGetErrors[keyof ListInterviewsApiV1InterviewsGetErrors];

export type ListInterviewsApiV1InterviewsGetResponses = {
  /**
   * Response List Interviews Api V1 Interviews Get
   * Successful Response
   */
  200: Array<InterviewRead>;
};

export type ListInterviewsApiV1InterviewsGetResponse =
  ListInterviewsApiV1InterviewsGetResponses[keyof ListInterviewsApiV1InterviewsGetResponses];

export type CreateInterviewFlatApiV1InterviewsPostData = {
  body: InterviewCreateFlat;
  path?: never;
  query?: never;
  url: "/api/v1/interviews";
};

export type CreateInterviewFlatApiV1InterviewsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateInterviewFlatApiV1InterviewsPostError =
  CreateInterviewFlatApiV1InterviewsPostErrors[keyof CreateInterviewFlatApiV1InterviewsPostErrors];

export type CreateInterviewFlatApiV1InterviewsPostResponses = {
  /**
   * Successful Response
   */
  201: InterviewRead;
};

export type CreateInterviewFlatApiV1InterviewsPostResponse =
  CreateInterviewFlatApiV1InterviewsPostResponses[keyof CreateInterviewFlatApiV1InterviewsPostResponses];

export type DeleteInterviewApiV1InterviewsInterviewIdDeleteData = {
  body?: never;
  path: {
    /**
     * Interview Id
     */
    interview_id: number;
  };
  query?: never;
  url: "/api/v1/interviews/{interview_id}";
};

export type DeleteInterviewApiV1InterviewsInterviewIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteInterviewApiV1InterviewsInterviewIdDeleteError =
  DeleteInterviewApiV1InterviewsInterviewIdDeleteErrors[keyof DeleteInterviewApiV1InterviewsInterviewIdDeleteErrors];

export type DeleteInterviewApiV1InterviewsInterviewIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteInterviewApiV1InterviewsInterviewIdDeleteResponse =
  DeleteInterviewApiV1InterviewsInterviewIdDeleteResponses[keyof DeleteInterviewApiV1InterviewsInterviewIdDeleteResponses];

export type ReadInterviewApiV1InterviewsInterviewIdGetData = {
  body?: never;
  path: {
    /**
     * Interview Id
     */
    interview_id: number;
  };
  query?: never;
  url: "/api/v1/interviews/{interview_id}";
};

export type ReadInterviewApiV1InterviewsInterviewIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadInterviewApiV1InterviewsInterviewIdGetError =
  ReadInterviewApiV1InterviewsInterviewIdGetErrors[keyof ReadInterviewApiV1InterviewsInterviewIdGetErrors];

export type ReadInterviewApiV1InterviewsInterviewIdGetResponses = {
  /**
   * Successful Response
   */
  200: InterviewRead;
};

export type ReadInterviewApiV1InterviewsInterviewIdGetResponse =
  ReadInterviewApiV1InterviewsInterviewIdGetResponses[keyof ReadInterviewApiV1InterviewsInterviewIdGetResponses];

export type UpdateInterviewApiV1InterviewsInterviewIdPatchData = {
  body: InterviewUpdate;
  path: {
    /**
     * Interview Id
     */
    interview_id: number;
  };
  query?: never;
  url: "/api/v1/interviews/{interview_id}";
};

export type UpdateInterviewApiV1InterviewsInterviewIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateInterviewApiV1InterviewsInterviewIdPatchError =
  UpdateInterviewApiV1InterviewsInterviewIdPatchErrors[keyof UpdateInterviewApiV1InterviewsInterviewIdPatchErrors];

export type UpdateInterviewApiV1InterviewsInterviewIdPatchResponses = {
  /**
   * Successful Response
   */
  200: InterviewRead;
};

export type UpdateInterviewApiV1InterviewsInterviewIdPatchResponse =
  UpdateInterviewApiV1InterviewsInterviewIdPatchResponses[keyof UpdateInterviewApiV1InterviewsInterviewIdPatchResponses];

export type ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetData =
  {
    body?: never;
    path: {
      /**
       * Application Id
       */
      application_id: number;
    };
    query?: {
      /**
       * Limit
       */
      limit?: number;
      /**
       * Offset
       */
      offset?: number;
    };
    url: "/api/v1/applications/{application_id}/pipeline-history";
  };

export type ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetError =
  ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetErrors[keyof ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetErrors];

export type ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponses =
  {
    /**
     * Response List Pipeline History For Application Api V1 Applications  Application Id  Pipeline History Get
     * Successful Response
     */
    200: Array<PipelineHistoryRead>;
  };

export type ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponse =
  ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponses[keyof ListPipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryGetResponses];

export type CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostData =
  {
    /**
     * Payload
     */
    body: PipelineHistoryUpdate | PipelineHistoryCreate;
    path: {
      /**
       * Application Id
       */
      application_id: number;
    };
    query?: never;
    url: "/api/v1/applications/{application_id}/pipeline-history";
  };

export type CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostError =
  CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostErrors[keyof CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostErrors];

export type CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponses =
  {
    /**
     * Successful Response
     */
    201: PipelineHistoryRead;
  };

export type CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponse =
  CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponses[keyof CreatePipelineHistoryForApplicationApiV1ApplicationsApplicationIdPipelineHistoryPostResponses];

export type ReadPipelineHistoriesApiV1PipelineHistoryGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Application Id
     * Filter by application id.
     */
    application_id?: number | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/pipeline-history";
};

export type ReadPipelineHistoriesApiV1PipelineHistoryGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadPipelineHistoriesApiV1PipelineHistoryGetError =
  ReadPipelineHistoriesApiV1PipelineHistoryGetErrors[keyof ReadPipelineHistoriesApiV1PipelineHistoryGetErrors];

export type ReadPipelineHistoriesApiV1PipelineHistoryGetResponses = {
  /**
   * Response Read Pipeline Histories Api V1 Pipeline History Get
   * Successful Response
   */
  200: Array<PipelineHistoryRead>;
};

export type ReadPipelineHistoriesApiV1PipelineHistoryGetResponse =
  ReadPipelineHistoriesApiV1PipelineHistoryGetResponses[keyof ReadPipelineHistoriesApiV1PipelineHistoryGetResponses];

export type CreatePipelineHistoryApiV1PipelineHistoryPostData = {
  body: PipelineHistoryCreateFlat;
  path?: never;
  query?: never;
  url: "/api/v1/pipeline-history";
};

export type CreatePipelineHistoryApiV1PipelineHistoryPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreatePipelineHistoryApiV1PipelineHistoryPostError =
  CreatePipelineHistoryApiV1PipelineHistoryPostErrors[keyof CreatePipelineHistoryApiV1PipelineHistoryPostErrors];

export type CreatePipelineHistoryApiV1PipelineHistoryPostResponses = {
  /**
   * Successful Response
   */
  201: PipelineHistoryRead;
};

export type CreatePipelineHistoryApiV1PipelineHistoryPostResponse =
  CreatePipelineHistoryApiV1PipelineHistoryPostResponses[keyof CreatePipelineHistoryApiV1PipelineHistoryPostResponses];

export type DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteData = {
  body?: never;
  path: {
    /**
     * History Id
     */
    history_id: number;
  };
  query?: never;
  url: "/api/v1/pipeline-history/{history_id}";
};

export type DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteError =
  DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteErrors[keyof DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteErrors];

export type DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    204: void;
  };

export type DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponse =
  DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponses[keyof DeletePipelineHistoryApiV1PipelineHistoryHistoryIdDeleteResponses];

export type ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetData = {
  body?: never;
  path: {
    /**
     * History Id
     */
    history_id: number;
  };
  query?: never;
  url: "/api/v1/pipeline-history/{history_id}";
};

export type ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetError =
  ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetErrors[keyof ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetErrors];

export type ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetResponses = {
  /**
   * Successful Response
   */
  200: PipelineHistoryRead;
};

export type ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetResponse =
  ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetResponses[keyof ReadPipelineHistoryApiV1PipelineHistoryHistoryIdGetResponses];

export type UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchData = {
  body: PipelineHistoryUpdate;
  path: {
    /**
     * History Id
     */
    history_id: number;
  };
  query?: never;
  url: "/api/v1/pipeline-history/{history_id}";
};

export type UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchError =
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchErrors[keyof UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchErrors];

export type UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponses = {
  /**
   * Successful Response
   */
  200: PipelineHistoryRead;
};

export type UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponse =
  UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponses[keyof UpdatePipelineHistoryApiV1PipelineHistoryHistoryIdPatchResponses];

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:8000" | (string & {});
};
